apiVersion: apps/v1
kind: Deployment
metadata:
  name: kat-admin-studio
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
    app.kubernetes.io/component: kat-admin-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kat-admin-studio
      app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
  template:
    metadata:
      labels:
        app: kat-admin-studio
        app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
        app.kubernetes.io/component: kat-admin-studio
    spec:
      containers:
        - name: kat-admin-studio
          image: ${KAT_ADMIN_STUDIO_IMAGE}
          ports:
            - containerPort: ${KAT_ADMIN_STUDIO_PORT}
          env:
            - name: NODE_ENV
              value: ${NODE_ENV}
