apiVersion: v1
kind: Service
metadata:
  name: kat-admin-studio
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
    app.kubernetes.io/component: kat-admin-studio
spec:
  type: ClusterIP
  selector:
    app: kat-admin-studio
  ports:
    - port: 80
      targetPort: ${KAT_ADMIN_STUDIO_PORT}
