apiVersion: v1
kind: Service
metadata:
  name: kat-admin-studio
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: kat-admin-studio
  ports:
    - port: 80
      targetPort: ${KAT_ADMIN_STUDIO_PORT}
