apiVersion: v1
kind: Service
metadata:
  name: kat-dynamic-portal
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: kat-dynamic-portal
  ports:
    - port: 80
      targetPort: ${KAT_DYNAMIC_PORTAL_PORT}
