apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kat-dynamic-portal-ingress
  namespace: ${NAMESPACE}
  annotations:
    networking.gke.io/managed-certificates: ${KAT_DYNAMIC_PORTAL_CERT_NAME}
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.gcp.kubernetes.io/force-cleanup: "true"
spec:
  ingressClassName: gce
  rules:
    - host: dynamicportal.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kat-dynamic-portal
                port:
                  number: 80
