apiVersion: v1
kind: Service
metadata:
  name: kat-api
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
    app.kubernetes.io/component: kat-api
  annotations:
    cloud.google.com/backend-config: >
      {"default": "${KAT_API_BACKEND_CONFIG}"}
spec:
  type: ClusterIP
  selector:
    app: kat-api
  ports:
    - name: http
      port: 80
      targetPort: 5001
      protocol: TCP
