apiVersion: v1
kind: Service
metadata:
  name: ktaiflow-ui
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
    app.kubernetes.io/component: ktaiflow-ui
spec:
  type: ClusterIP
  selector:
    app: ktaiflow-ui
  ports:
    - port: 80
      targetPort: 80
