x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1

  deployer:
    type: manifest
    image: gcr.io/elexratio/deployer:2.0

properties:
  APP_INSTANCE_NAME:
    type: string
    title: Application Instance Name
    description: Name of this deployed instance.
    default: elexratio
    pattern: "^[a-z0-9-]+$"

  NAMESPACE:
    type: string
    title: Kubernetes Namespace
    default: elexratio

  DOMAIN:
    type: string
    title: Base Domain
    description: Base domain for ingress hosts (example: example.com)
    pattern: "^[a-zA-Z0-9.-]+$"

required:
  - APP_INSTANCE_NAME
  - NAMESPACE
  - DOMAIN
