apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ktaiflow-api-ingress
  namespace: ${NAMESPACE}
  annotations:
    networking.gke.io/managed-certificates: ${KTAIFLOW_API_CERT_NAME}
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: gce
  rules:
    - host: aiflow-api.${DOMAIN}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ktaiflow-api
                port:
                  number: 80

          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: ktaiflow-api
                port:
                  number: 80

          - path: /health
            pathType: Prefix
            backend:
              service:
                name: ktaiflow-api
                port:
                  number: 80
