apiVersion: v1
kind: Service
metadata:
  name: ktaiflow-api
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
    app.kubernetes.io/component: ktaiflow-api
  annotations:
    cloud.google.com/backend-config: >
      {"default": "${KTAIFLOW_API_BACKEND_CONFIG}"}
spec:
  type: ClusterIP
  selector:
    app: ktaiflow-api
  ports:
    - name: http
      port: 80
      targetPort: ${KTAIFLOW_API_PORT}
      protocol: TCP
