apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kat-api-ingress
  namespace: ${NAMESPACE}
  annotations:
    networking.gke.io/managed-certificates: ${KAT_API_CERT_NAME}
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.gcp.kubernetes.io/force-cleanup: "true"
spec:
  ingressClassName: gce
  rules:
    - host: api.${DOMAIN}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kat-api
                port:
                  number: 80

          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: kat-api
                port:
                  number: 80

          - path: /RbacDashboard
            pathType: Prefix
            backend:
              service:
                name: kat-api
                port:
                  number: 80

          - path: /health
            pathType: Prefix
            backend:
              service:
                name: kat-api
                port:
                  number: 80
