apiVersion: apps/v1
kind: Deployment
metadata:
  name: kat-dynamic-portal
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
    app.kubernetes.io/component: kat-dynamic-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kat-dynamic-portal
      app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
  template:
    metadata:
      labels:
        app: kat-dynamic-portal
        app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
        app.kubernetes.io/component: kat-dynamic-portal
    spec:
      containers:
        - name: kat-dynamic-portal
          image: ${KAT_DYNAMIC_PORTAL_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: ${NODE_ENV}
