apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktaiflow-ui
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
    app.kubernetes.io/component: ktaiflow-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktaiflow-ui
      app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
  template:
    metadata:
      labels:
        app: ktaiflow-ui
        app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
        app.kubernetes.io/component: ktaiflow-ui
    spec:
      containers:
        - name: ktaiflow-ui
          image: ${KTAIFLOW_UI_IMAGE}
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: ${NODE_ENV}
