apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktaiflow-api
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
    app.kubernetes.io/component: ktaiflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktaiflow-api
      app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
  template:
    metadata:
      labels:
        app: ktaiflow-api
        app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
        app.kubernetes.io/component: ktaiflow-api
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT}
      containers:
        - name: ktaiflow-api
          image: ${KTAIFLOW_API_IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "GcpDevelopment"
            - name: CLOUD_PLATFORM
              value: "Gcp"
            - name: GCP_PROJECT_ID
              value: ${GCP_PROJECT_ID}
            - name: SQL_BASE
              value: "GKE"
            - name: ASPNETCORE_URLS
              value: "http://*:8080"

          readinessProbe:
            tcpSocket:
             port: ${KTAIFLOW_API_PORT}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
             port: ${KTAIFLOW_API_PORT}
            initialDelaySeconds: 60
            periodSeconds: 30